#spring.application.name=gateway

spring: 
  application:
    name: gateway
  profiles:
    active: default

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: clans_service
          uri: lb://clanes-crud #se debe colocar el mismo nombre que esta en el archivo yaml en clanes name
          predicates:
            - Path=/clan/** # es la ruta que termina en controller y empieza en el aplication.yaml
        - id: team_leader_service
          uri: lb://team-leader-service #se debe colocar el mismo nombre que esta en el archivo yaml en clanes name
          predicates:
            - Path=/api/v1/team-leader/** # es la ruta que termina en controller y empieza en el aplication.yaml

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
